### ISSUE TITLE
Generated_at and created_at using different time zones

### ISSUE THREAD

**Issue by hellam** [seshac/otp-generator#8]
Please include timezone configuration in the config file because Carbon::now() is using default time zone configured in php.ini and not the timezone defined in the .env file.

**Comment by seshac** [comment]
thank you @hellam, I will do that one!

**Comment by hellam** [comment]
Hello @seshac, when are you planning to work on this issue?

**Comment by sesha008** [comment]
Will do on this weekend. If you want early, feel free to create a PR.

**Comment by hellam** [comment]
Weekend is fine. I will appreciate it.

**Comment by hellam** [comment]
Hi, did you manage to work on it?

**Comment by seshac** [comment]
Actually, Laravel will do that.

To update the timezone, just update the timezone at config/app.php

for more:  vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/LoadConfiguration.php

**Comment by hellam** [comment]
I did that already in the config/app.php but there was no change and that's why I raised the issue here

**Comment by seshac** [comment]
Please clear the config and cache and check again.

**Comment by hellam** [comment]
![image](https://user-images.githubusercontent.com/22488154/129656975-41b07e93-592d-44d4-a4ab-2003a158ecf5.png)
Have a look at this database image and help explain why generated at is using different timezone from the rest.

**Comment by hellam** [comment]
I cleared the config and cache but the same issue persists

**Comment by seshac** [comment]
> ![image](https://user-images.githubusercontent.com/22488154/129656975-41b07e93-592d-44d4-a4ab-2003a158ecf5.png)
> Have a look at this database image and help explain why generated at is using different timezone from the rest.

I will check this and let you.

**Comment by hellam** [comment]
Okay thanks, I will be waiting for your feedback.

**Comment by YosraHamza** [comment]
The same problem happened to me, I solved it by preventing using current timestamp on update as the db timezone is different from the app timezone
